# Generated by Django 5.0 on 2024-01-09 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mains', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stellas',
            name='stella_name_code',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
