# Generated by Django 5.0 on 2024-01-09 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mains', '0002_stellas_stella_name_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='kirinuky',
            name='kirinuky_day',
            field=models.DateField(null=True),
        ),
    ]
