# Generated by Django 5.0 on 2024-06-01 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mains', '0003_kirinuky_kirinuky_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requests_category', models.CharField(max_length=20)),
                ('requests_con', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterModelOptions(
            name='stellas',
            options={'ordering': ['for_order']},
        ),
        migrations.AddField(
            model_name='stellas',
            name='for_order',
            field=models.IntegerField(default=0),
        ),
    ]
